
	<main class="main3child">
		<h2>
			Comment apprendre et de qui?
		</h2>
		
		<section class="voie1 marginBottom25">
			
			<h3 id="autodidacte">La formation autodidacte</h3>
			<p>La formation autodidacte nécessite une plus grande organisation. En effet, vous êtes livré à vous même sans personne pour vous encadrer. Si vous optez pour une formation de ce type, il vous faut établir un plan d'apprentissage strict.</p>
			<ol class="upperHexa">
				<li>
					<h4 id="site_pro">Les sites professionnels</h4>

					<ul>
						<li><a href="https://openclassrooms.com/fr/" target="_blank">Openclassroom: </a>
						Ce site offre des tutos écris et en vidéo, un accès à un forum de discussion au cas où vous souhaiteriez partager vos expériences ou demander de l'aide. Enfin, il offre aussi des formations payantes qui vous donnerons accès à des titres pro reconnus au RNCP, allant jusqu'à bac+5.</li>
						<li><a href="https://developer.mozilla.org/fr/" target="_blank">Developpez.mozilla.org/fr: </a>
						Ce site est vraiment utile en complément d'un tuto vidéo car il apporte plus de précisions sur un domaine spécifique. Il vous permet également d'avoir une autre explication sur un sujet que vous n'auriez pas saisi avec un autre tuto. Ce site est pour moi l'Agora de la programmation.</li>
					</ul>
				</li>

				<li>
					<h4 id="site_particuliers">Sites de particuliers</h4>

					<ul>
						<li><a href="https://www.pierre-giraud.com/" target="_blank">Site de Pierre Giraud:</a>
							Ce site est ce qu'il y a de plus structuré en matière d'apprentissage des langages de programmation. L'on vous apprend en outre les bonnes pratiques pour coder. Toutefois, il date de 2015-2016, il n'est donc plus aussi complet qu'il l'était à l'époque. En outre, il s'agît d'un apprentissage sans frameworks. Il s'agît cependant d'un excellent pédagogue. C'est le site que je recommanderai à tous les débutants.
						</li>	
						<li><a href="https://www.grafikart.fr/" target="_blank">Site de Grafikart:</a>
						Ce site est selon moi le parfait complément à celui de Pierre Giraud. Il est plus actuel, axé sur de nombreux problèmes spécifiques que vous rencontrerez. Vous pouvez bien entendu apprendre l'intégralité de la programmation uniquement avec  Grafikart. Sachez cependant que cela sera payant. Je vous rassure tout de suite, on est loin des 5000 euros demandés en moyenne par les écoles. L'accès à ses cours ne coûtent qu'une trentaine d'euros annuel.</li>					
					</ul>
				</li>
			</ol>
			<p class="conclusion">Je recommanderai de suivre les cours de Pierre Giraud pour les langages de programmation (HTML, CSS, JS et PHP) et en parallèle, ceux de Grafikart sur les outils de programmation (NodeJS, Git...) et autres. Dès que vous bûchez ou que vous avez besoin de plus amples renseignements, Openclassroom et Developpez.mozilla seront vos meilleurs amis.</p>
		</section>

		<section class="voie2 marginBottom25">
			<h3 id="academique">La voie académique</h3>
			<p>Elle passe par la reprise de l'école et demande donc beaucoup de temps. Le problème majeur est que le nombre de places étant limité, les personnes en reconversion n'y sont pas prioritaires.</p>

			<ol>

				<li>
					<h4 id="ecole">Les écoles</h4>

					<ul class="lowerAlpha">
						<li>
							<h5>Les formation à distance:</h5>

							<ul>
								<li>
									<a href="http://www.cnam.fr" target="_blank">Le Cnam</a> ou <a href="http://www.cned.fr/" target="_blank">le Cned :</a>
								</li>

								<li><p>Si vous ne voulez ou ne pouvez pas entrer en école classique, l'un comme l'autre constituera une solution  intéressante. Sachez cependant que les formations dispensées par le Cnam ont généralement une meilleure réputation que celle venant du Cned.</p></li>
							</ul>
						</li> 
						<li>
							<h5>Ecoles classiques:</h5>
							<ul>

								<li><p>Il s'agît de toutes les écoles publiques ou privées habilitée à remettre des diplômes du système LMD. C'est à dire Licence, Master, Doctorat. Le problème est que lorsqu'on est en reconversion, l'on a généralement passé la trentaine et il n'est pas aisé de se retrouver avec des jeunes. En outre l'on a pas forcément choisi le bon cursus au lycée pour faciliter les dossiers d'acceptation.</p></li>
							</ul>
						</li>
					</ul>
				</li>

				<li>
					<h4 id="cursus">Les cursus</h4>

					<ul>
						<li>
							<ul class="ulCercle">

								<li><span class="bold">Bac+2:</span> BTS SIO option slam, prépa math option informatique, DUT informatique, L2 informatique ou Technicien développeur du Cnam</li>
								<li><span class="bold">bac+3:</span> Licence informatique ou licence pro dans le domaine. Attention, si vous choisissez une licence pro, sachez que vous ne serez pas prioritaire en cas de poursuite d'études.</li>
								<li><span class="bold">bac+5:</span> Ingénieur informatique (AISL ou Système d'Information) après un bac +2. Il y a également le Master informatique après un bac+3</li>
							</ul>
						</li>
					</ul>
				</li>
			</ol>

			<p>Attention, le titre d'ingénieur est souvent préféré au diplôme de master. Sur la durée, cela ne constituera pas de problème: vous vous retrouverez à peu près aux mêmes positions. Cependant, vous ne démarrerez pas forcément de la même manière. Il peut y avoir au début de légères différences de salaire. Il faudra faire appel à vos talents de négociateur dans ce cas. La rapidité de l'avancement peut s'en trouver également affectée. Enfin, certaines grosses boîtes ne prioriseront que certains profils. Cependant, dans ce cas de figure, ce n'est pas le type de diplôme que vous aurez mais la côte de l'école dont vous serez issus qui comptera. </p>
			<p>Paradoxalement, les écoles privées d'informatique ne vous donnent pas plus d'avantages que les écoles publiques. Beaucoup d'écoles privées ne livrent pas de diplômes mais des titres professionnels qui n'ont aucune valeur académique (LMD).
			Les cursus commencés en LMD peuvent d'ailleurs être poursuivit en formation professionnelle certifiante (RNCP). Toutefois, sauf exception, le contraire n'est pas exact.</p>
		</section>

		<section class="voie3">
			<h3 id="form_pro">La voie professionnelle</h3>
			<p>Cette solution coupe la poire en deux. Elle permet d'être encadré durant sa formation ainsi que l'obtention de titres professionnels reconnus par l'Etat.</p>
			<ol>

				<li><h4 id="rncp">Les titres RNCP</h4></li>

				<li><p>Si les diplômes sont reconnus dans les milieux académique et professionnel, les titres RNCP ne le sont que par le milieu professionnel. Cela ne signifie pas qu'ils ont une moindre valeur puisque l'Etat reconnaît aussi bien l'un que l'autre. Le problème est que vous pourrez tombez sur quelqu'un de la vieille école pour qui, seul le titre d'ingénieur assure réellement les compétences en programmation. Pour ces personnes, vous posséderez un sous-diplôme. Ils sont pourtant soumis aux mêmes grades:</p></li>
				<li>
					<ul class="bold ulCercle">
						<li>Niveau IV = Bac</li>
						<li>Niveau III = Bac+2</li>
						<li>Niveau II = Bac+3/4</li>
						<li>Niveau I = Bac+5 et +</li>
					</ul>
				</li> 
				<li><p>Le véritable atout des écoles privées qui fonctionnent pour nombres d'entre elles, par la délivrance de titres professionnels, est le style d'apprentissage. Vous apprenez par projets. Un titre s'obtient avec la réalisation de ces projets prédéfinis. Il ne s'agît pas d'examens à passer par matière où vous pouvez échouer encore et encore. Vous rentrez dans le bain immédiatement mais chaque projet réalisé vous rapproche de l'obtention du titre. Les projets se font parfois en groupe donc cela vous permettra d'apprendre à travailler avec les autres. C'est une méthode d'apprentissage qui se veut empirique. Pour les personnes qui ont de grande facilité durant les excercices mais qui stressent durant les examens, cela sera parfait. Pour les personnes qui ne souhaitent pas retourner sur les bancs de l'école aussi. </p></li>


				<li><h4>Les types de formation</h4></li>
				<li><p>Les formations sont diverses et variées car elles amènent à la reconnaissance de l'Etat dans un corps de métiers. Il existe par exemple, des titres pro de développeur intégrateur web, d'autres de développeur d'applications, de chef de projet informatique... Vous pouvez trouver la liste de tous les titres sur le <a href="http://www.rncp.cncp.gouv.fr/" target="_blank">répertoire national des titres professionnels.</a></p></li>


				<li>
					<h4 id="ecole_pro">Les écoles</h4>
					<ul>
						<li><p class="bold">La plus cotée:</p>

							<ul>
								<li><a href="https://www.hetic.net/" target="_blank">Hetic:</a></li> 
								<li>Elle est aujourd'hui préférée à la plus part des écoles d'ingénieur! Elle classée dans la majorité des sondages comme l'une des 3 meilleures école d'informatique en France.</li>
							</ul>
						</li>
						<li><p class="bold">Les plus populaires:</p>

							<ul class="ulCercle">
                                <li><a href="https://3wa.fr/" target="_blank">3w Academy</a></li>
                                <li><a href="http://www.efficom.fr/" target="_blank">Efficom</a></li>
								<li><a href="https://openclassrooms.com/" target="_blank">OC</a></li> 
								<li><a href="https://www.webschoolfactory.fr" target="_blank">La WebschoolFactory</a></li>
								<li><a href="https://www.hitema.fr/" target="_blank">Hitema</a>...</li>
							</ul>
						</li>
						<li><p class="bold">Celles que je ne ferais pas: </p>
							<ul class="ulCercle">
								<li><a href="http://cesi-alternance.fr/" target="_blank">CESI</a> </li>
								<li><a href="https://www.afpa.fr/" target="_blank">AFPA</a></li>
								<li><a href="http://www.nextadvance.fr" target="_blank">NextAdvance</a>
									<p>(C'est mon avis, que cela ne vous empêche en rien de tenter l'expérience. Cependant mes critères dans la sélection d'une école refusent catégoriquement: une absence de matériel fourni, un surnombre dans les salles de classes et un trop plein d'avis négatifs. )</p>
								</li> 

							</ul>
						</li>
					</ul>
				</li>

			</ol>

			<p>N'oubliez pas que ces écoles sont privées. Ce sont donc des machines à sous. Quant bien même la qualité d'enseignement serait au rendez-vous, vous pouvez ne pas avoir suffisamment  de base pour terminer le cursus; pourtant certaines vous promettront monts et merveilles en faisant fi de vos capacités. Il est impératif que vous vous formiez en autodidacte pour prendre de l'avance ou du moins rattraper votre retard. Cela peut être en informatique mais également en mathématique. Vous risquez sinon de vous retrouver perdus lors de votre formation et aurez l'impression de vous être fait avoir. Ne comptez pas sur un vendeur pour vous dire : </p>
			<p class="span_avis">"Mon produit est bien mais il vaut mieux que vous l'achetiez l'année prochaine, quand vous serez prêt financièrement!!!"</p>

		</section>

	</main>
