<main>
			<div class="presentation">
				<p>Bonjour, </p> 
				<p>
                    Je m'appelle <span class="purple">Bahamut0</span> (pour des raisons de paranoïa, ma véritable identité sera remplacée par ce surnom). Si tu te trouves sur ce site, c'est que tu as plusieurs possibilités entre les mains, et par conséquent, un choix à faire.
				<p/>
				<p class="pad10">
                    <img src="<?php echo BASE_URL?>/img/matrix_pills.jpg" alt="Pilules de Matrix">
                </p>
				<ul>
					<li class="pb">Demeurer fidèle à tes habitudes et rester dans la même branche d'activité.  </li>
					<li class="pr">Découvrir la vérité dissimulée derrière des lignes de codes et devenir développeur web !</li>
				</ul>

				<p class="point">...</p>

				
				<p>Personnellement, je n'ai pas hésité. J'ai opté pour la pilule rouge:
					<span class="bold red">la reconversion.</span></p><br>	
				<p class="pad10"><img src="<?php echo BASE_URL?>/img/matrix_choice.jpg" alt="choix de la pillule rouge"></p>
				
				<p>Hélas, si tôt plongé dans ce nouveau monde, je me suis très vite noyée dans un marasme d'informations et de propositions. Comment se former? Où se former? Les financements. Les diplômes et titres professionnels. Des logiciels inconnus. Un vocabulaire nouveau. Une panoplie de Youtubers qui me jurent de me transformer en génie! </p>	
				<p>
                    <iframe src="https://giphy.com/embed/QuO2xVq2JrSLe" width="480" height="360" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/house-everyone-sleep-QuO2xVq2JrSLe">via GIPHY</a></p>
                </p>
				<p>Malgré tout, avec un peu de patience, d'organisation et beaucoup de motivation, j'ai pu faire un tri. Encore mieux, après quelques mois d'apprentissage intensif au centre de formation 3W Academy, j'en sors enrichie de nouvelles connaissances.</p>
				<p>Ce site a vocation de transmettre les leçons que j'ai apprises afin que la pilule passe mieux de votre côté.</p>
				<br>
				<blockquote class="bolder-30px "><i class="fas fa-quote-left"></i>Mais attention: Tout ce que je vous offre, c'est la vérité. Je ne peux que vous montrer la porte, c'est à vous qu'il appartient de la franchir.<i class="fas fa-quote-right"></i></blockquote>
			</div>

</main>