
	<main class="main1child ide">

		<h2>IDE et EDT</h2>

		<section class="child1">
			<h3 id="choisir_ide">Comment choisir entre les deux?</h3>
			<ul class="square">
				<li>Un EDT (éditeur de texte) se différencie d'un IDE (Integrated Developement Environment = environnement de développement intégré). Le premier se contente normalement de vous permettre d'écrire votre code, le second élabore tout un environnement vous aidant à réaliser votre projet. Cela explique la raison pour laquelle, les IDE sont largement préférées par les entreprises.</li> 
				<li>Cependant, les améliorations récentes permettent à certains EDT de se comporter comme des IDE ou presque. Parce que nombres de ces EDT sont gratuit, ils seront souvent choisis pour les plus petits projets. Si vous travaillez en agence, le choix vous sera rarement laissé et vous devrez vous adapter. Dans le cas contraire, c'est à vous de voir.</li> 
				<li>Pour résumer les points forts de l'IDE sont: l’auto complétion, la coloration syntaxique, une interface pour les tests, une gestion des fichiers du projet, un gestionnaire VCS, un débuggeur avec IHM, pluggin maven, etc...</li> 
				<li>Mon avis est qu'il faut choisir en fonction de vos besoins. Le développement web, peut se passer d'un IDE à condition d'avoir un EDT au top: ATOM, SublimeText ou VS Code. Ces derniers possèdent en effet la grande majorité des atouts des IDE. En revanche vos projets PHP en POO qui utilisent une structure MVC auront besoin d'un IDE.</li></ul>
			</section>
			<section class="child2">	
				<h3 id="best_ide">Top 3 EDT et Top 3 IDE</h3>
				<table>
					<tr>
						<th>EDT</th>
						<th>Description</th>
						<th>IDE</th>
						<th>Description</th>
					</tr>
					<tr>
						<td><a href="https://www.sublimetext.com/" target="_blank">Sublime Text</a></td> 
						<td>Léger, rapide, il possède une panoplie de pluggins. Il s'assimile ainsi à un IDE. Très réactif, parfois même trop réactif. Ces packages sont téléchargeable depuis l'EDT.</td>
						<td><a href="https://www.jetbrains.com/phpstorm/" target="_blank">PhpStorm</a></td>
						<td>Un IDE complet pour de nombreux langages de programmation. Parfait pour les sites e-commerce. Le hic: son prix. On dit que la perfection n'a pas de prix. Mais on a pas tous le même portefeuille, n'est-ce pas? A présent que j'utilise ce logiciel, je peux vous confirmer qu'il est difficile de s'en passer. Mais vous avez cependant une technique. Vous pouvez désinstaller tous les mois la version d'évaluation et la réinstaller pour profiter indéfiniment de IDE. </td>
					</tr>	
					<tr>
						<td><a href="https://atom.io/" target="_blank">Atom</a></td>
						<td>Superbe après avoir téléchargé les pluggins via Github. Il est intuitif et réactif à souhait. Mais ses performences jouent parfois sur sa lenteur. Le grand bonus: il est open source! Il y a donc de nombreuses edit pour l'améliorer.</td>
						<td><a href="https://www.jetbrains.com/webstorm/" target="_blank">WebStorm</a></td>
						<td>Cela se finit par Storm pour une bonne raison. Il s'agît de la même famille. C'est la gamme Jetbrains. Hélas cette version se veut moins complète puis que vous ne pourrez pas faire grand-chose en PHP! Mais pour les adeptes du JavaScript, vous pouvez foncer! Cependant comme PhpStorm, l'IDE vous évitera de requérir à des logiciels supplémentaires: rest, api, git... </td>
					</tr>
					<tr>
						<td><a href="https://code.visualstudio.com/" target="_blank">Visual Studio Code</a></td>	
						<td>Très bon EDT, qui comme Atom et ST, vous donnera l'impression de travailler avec un IDE. Il fonctionne également avec NodeJs  mais ne possède pas ses problèmes de lenteur. Seul Bémol, il lui manque quelques pluggins présents sur Atom et SublimeText.</td>
						<td><a href="https://netbeans.org/downloads/" target="_blank">Netbeans</a></td>
						<td>A part sa lenteur et la fréquence tardive d'arrivée de pluggins, il n'a que des qualités. Adapté aussi bien aux experts qu'aux débutants. Il suit les différents langages de programmation du développeur web. Il possède un bon système de vérification d'erreurs...</td>		
					</tr>
				</table>
			</section>	
		</main>

		