
	<main class="main2child langages" id="langage">
		<h2 class="titre2">Langages de programmation, Frameworks et CMS</h2>
		<p class="intro">Si les étapes précédentes se focalisaient sur la préparation au développement, celle-ci entre pleinement dans le domaine puisqu'elle permet de développer. Pour se faire, l'on peut simplement se servir des langages de programmation que l'on associera généralement aux Frameworks. Enfin l'on peut également développer grâce aux CMS. Pour comprendre comment, il convient de définir et faire la distinction entre les trois.</p>

		<!-- explication des langages de programmation-->


		<ol class="upperHexa">
			<li>
				<h3>Les langages de programmation:</h3>

				
				<p>J'énumerai simplement les principaux langages du développement web: HTML, CSS, JavaScript et PHP. A utiliser avec un langage de manipulation des données appelé SQL (Structured Query Language) conjointement avec un système de gestion de base de données : MySQL, PostgreSQL, Oracle Database... Vous pouvez utiliser en complément ou à la place d'autres langages de programmation comme Python et Ruby. Vous ne les utiliserez pas forcément tous. Cela dépendra du type de sites web que vous souhaitez concevoir.</p>


				<!-- Tableau 1: Langages de programmation-->
				<table>
					<tr>
						<th>Langage</th>
						<th>Description</th>
						<th>Langage</th>
						<th>Description</th></tr>
						<tr>
							<td>HTML 5</td>
							<td><p>HTML, l'HyperText Markup Language  ou le langage de balisage hypertexte, permet de structurer sémantiquement et logiquement le contenu des pages, d’inclure des ressources multimédias (images, vidéos...), des formulaires de saisie et des programmes informatiques.</p></td>
							<td>CSS</td>
							<td><p>CSS est l'acronyme de « Cascading Style Sheets » ce qui signifie « feuille de style en cascade ». Le CSS correspond à un langage informatique permettant de mettre en forme des pages web (HTML ou XML)</p></td></tr>
							<tr>
								<td>JavaScript</td>
								<td><p>JavaScript est un langage de script orienté objet. Ce langage à la particularité de s'activer sur le poste client, en d'autres mots c'est votre ordinateur qui va recevoir le code et qui devra l'exécuter. L'une de ses plus belle fonctionnalités est la possibilité d'exécuter un code sans devoir être contraint de recharger une page web.</p></td>
								<td>PHP</td>
								<td><p>PHP est un acronyme récursif de "PHP: Hypertext Preprocessor". Ce langage de programmation libre est principalement utilisé pour produire un site web dynamique. Cela fonctionne via un serveur HTTP3, mais peut également fonctionner comme n'importe quel langage interprété de façon locale. Il est courant que ce langage soit associé à une base de données, tel que MySQL. PHP est un langage impératif orienté objet.</p></td>
							</tr>
						</table>
            </li>
					<!-- explications sur les frameworks-->


            <li>
                <h3 id="frameworks">Les frameworks:</h3>
                <p>"Un framework est un ensemble de scripts développés par une société informatique ou un particulier en vue de faciliter le travail du développeur". Ces scripts vont créer un squelette sur lequel vous pourrez travailler.</p>


                <!-- Tableau 2: Frameworks-->
                <table>
                    <tr>
                        <th>Frameworks</th>
                        <th>Description</th>
                        <th>Frameworks</th>
                        <th>Description</th>
                    </tr>
                    <tr>
                        <td>Bootstrap</td>
                        <td><p>Le meilleur ou du moins le framework CSS le plus poplulaire. Créé par Twiter, Bootstrap est un framework CSS qui améliorent ses fonctionnalités. Il peut aussi travailler à la place du CSS. Il peut aussi en partie améliorer le HTML et le JS. En effet, Bootstrap aide à la présentation graphique et au positionnement par un système de classes spéciales. Le problème c'est qu'au final, les layout des sites ont tendance à tous se ressembler.</p></td>
                        <td>Laravel</td>
                        <td><p> Sans doute le meilleur framework php. "Laravel est un framework web open-source écrit en PHP2 respectant le principe modèle-vue-contrôleur et entièrement développé en programmation orientée objet. Laravel est distribué sous licence MIT, avec ses sources hébergées sur GitHub. Laravel fournit des fonctionnalités en termes de routage de requête, de mapping objet-relationnel (un système baptisé Eloquent implémentant Active Record), d'authentification, de vue (avec Blade), de migration de base de données, de gestion des exceptions et de test unitaire2."</p></td>
                    </tr>
                    <tr>
                        <td>Symfony</td>
                        <td><p>L'un des meilleurs frameworks php. Orienté-objet et modulaire, le framework Symfony permet d'optimiser les performances, la maintenance et l'évolutivité de sites très exigeants techniquement ou à forte charge. Il se révèle aussi incontournable pour gérer les contenus multilingues dans votre site internet. Symfony2 est un framework lourd et peut affecter les performances.</p></td>
                        <td>CakePHP</td>
                        <td>"Un framework parfait pour les non initiés qui veulent apprendre à développer des applis Web assez rapidement.La version 3.0 de CakePHP est fraîche et fonctionnelle, utilise la convention MVC pour les gens qui aiment l’ordre et la configuration est pas compliqué. Tout simplement, aucun fichier XML ou Yaml n’est nécessaire. Les outils de sécurité sont un gros plus pour CakePHP qui vient avec des fonctionnalités qui évitent les injections XSS et SQL ainsi que des outils de validation de formulaire. Le développement est toujours actif et la documentation est simple à comprendre."</td>
                    </tr>
                    <tr>
                        <td>Django</td>
                        <td>"Django est un framework Backend Open Source développé en Python. Il a été spécialement créé pour réaliser des sites Web puissants et de haut niveau. Voici quelques sites réalisés avec le framework Django." (exemple: mozilla)</td>
                        <td>Ruby on rails</td>
                        <td>"RoR est le framework MVC libre le plus populaire. Ce framework a été conçu pour développer des applications Web plus rapidement. Il permet aux développeurs de créer des fonctionnalités avec moins de code que d'autres frameworks." (exemple : github)</td>
                    </tr>
                    <tr>
                        <td>Angular JS</td>
                        <td>C'est le frameworks n°1 pour JavaScript. Son atout principal est de combiner aisément le JS au HTML et CSS. framework MVVM à part entière avec une liaison de données recto-verso. "AngularJs est un framework Open Source développé par Google en JavaScript. Il offre un haut niveau d'interactivité particulièrement apprécié en développement Front End des applications Web (SaaS, comparateurs, plateformes interactives)". Exemple: Youtube</td>
                        <td>React.js</td>
                        <td>C'est le framework n°2 en JavaScript. Il possède une écriture plus facile à comprendre pour les débutants par rapport à Angular JS. "React est créé et maintenu par Facebook. React n'est pas un framework Full-Stack comme le sont les deux précédents. Il fourni seulement les vues et les fonctions de callback pour rendre le code HTML." (ex: Facebook)</td>
                    </tr>
                </table>
            </li>

					<!--explication sur les CMS-->


            <li>
                <h3 id="cms">CMS:</h3>
                <p>C'est l'acronyme de "Content Management System", soit en français, « Système de gestion de contenu ». Il s'agit d'un programme informatique utilisant une base de données et permettant de gérer de A et Z l'apparence et le contenu d'un site web. Bref, ce n'est plus un squelette mais une poupée que vous habillez.</p>



                <!-- Tableau 3: CMS-->
                <table>
                    <tr>
                        <th>CMS</th>
                        <th>Description</th>
                        <th>CMS</th>
                        <th>Description</th>
                    </tr>
                    <tr>
                        <td>Wordpress</td>
                        <td><p>Ce CMS libre distribué par Automattic, s'est d'abord fait connaître comme créateur de blog. Ecrit en PHP et utilisant la base de donnée MySQL, il su gagner en popularité. En chiffre: 1 site sur 4 a pour ossature Wordpress en proposant notamment des sites vitrines voire dynamique.</p></td>
                        <td>Drupal</td>
                        <td><p>"Plus complexe avec son organisation des publications sous forme de nœuds, Drupal est idéal pour diffuser les contenus à forte pérennité, comme les présentations institutionnelles ou les archives documentaires. La solution est adaptée aux projets avec plus d'envergure technique comme la connexion avec des solutions tierces à votre site internet."</p></td>
                    </tr>
                    <tr>
                        <td>Prestashop</td>
                        <td><p>"PrestaShop autorise la création de site e-commerce sur-mesure quel que soit votre business. Sa fluidité, son intuitivité et ses fonctionnalités très riches vous aident à convertir plus efficacement. Notre agence web certifiée PrestaShop Partner Platinum sur Paris et Bordeaux vous fait profiter de ces atouts pour créer et booster votre activité e-commerce."</p></td>
                        <td>Magento</td>
                        <td><p>"Magento constitue une autre solution de qualité pour les sites e-commerce de toute taille. Pratiques, ses modules permettent la prise en charge sans complication d'outils marketing comme l'affiliation, le parrainage et la fidélisation."</p></td>
                    </tr>

                </table>
            </li>
        </ol>
        <small class="italic">Les définitions entre guillemets sont tirées du site wikipedia.</small>
    </main>
