<!DOCTYPE html>
<html lang="fr">
	<head>
		<title>Reconversion Développeur Web</title>
		<meta charset="utf-8">
		<meta name=viewport content="width=device-width, initial-scale=1">
		<meta name="description" content="Comment réussir sa reconversion en développeur web? Préparation, Formation
		et financement. La pillule verte des reconvertis. ">
		<link rel="stylesheet" href="<?php echo BASE_URL?>/fontawesome/css/all.css">
		<link rel="stylesheet" href="<?php echo BASE_URL?>/css/reset.css">
		<link rel="stylesheet" href="<?php echo BASE_URL?>/css/style.css">
        <link rel="stylesheet" href="<?php echo BASE_URL?>/css/dragon_slayer.css">
        <link href="https://fonts.googleapis.com/css?family=Lato|Oswald" rel="stylesheet">

	</head>
    <body>
        <div class="container">
            <header>
                <h1>Reconversion Développeur Web</h1>
                <p>La pilule verte des reconvertis!</p>
                <a href="mailto:bahamut007@outlook.fr" class="contact"><i class="fas fa-envelope"></i>Me contacter</a>

                <nav>
                <ul class="menu">
                    <li>
                        <a href="<?php echo route("home"); ?>"><img src="<?php echo BASE_URL?>/img/homeM.png"></a>

                    </li>
                    <li class="has-children">
                        <a href="<?php echo route("preparation"); ?>">Préparation</a>
                        <ul class="sous-menu">
                            <li class="has-children"><a href="<?php echo route("preparation"); ?>#environnement">L'environnement</a>
                                <ul class="sous-menu">
                                    <li><a href="<?php echo route("preparation"); ?>#os">Système d'exploitation</a></li>
                                    <li><a href="<?php echo route("preparation"); ?>#clavier">Clavier</a></li>
                                    <li><a href="<?php echo route("preparation"); ?>#cli">L'invite de commande</a></li>
                                    <li><a href="<?php echo route("preparation"); ?>#vocabulaire">Vocabulaire informatique</a></li>
                                </ul>
                            </li>
                            <li class="has-children"><a href="<?php echo route("preparation"); ?>#metier">Le métier</a>
                                <ul class="sous-menu">
                                    <li><a href="<?php echo route("preparation"); ?>#client">Le client</a></li>
                                    <li><a href="<?php echo route("preparation"); ?>#protypeur">Le protypeur</a></li>
                                    <li><a href="<?php echo route("preparation"); ?>#webdesigner">Le webdesigner</a></li>
                                    <li><a href="<?php echo route("preparation"); ?>#integrateur">L'intégrateur</a></li>
                                    <li><a href="<?php echo route("preparation"); ?>#front">Le développeur front-end</a></li>
                                    <li><a href="<?php echo route("preparation"); ?>#back">Le développeur back-end</a></li>
                                </ul>

                            </li>
                        </ul>
                    </li>
                    <li class="has-children">
                        <a href="<?php echo route("teachers"); ?>">Enseignement</a>
                        <ul class="sous-menu">
                            <li class="has-children">
                                <a href="<?php echo route("teachers"); ?>#autodidacte">La formation autodidacte</a>
                                <ul class="sous-menu">
                                    <li><a href="<?php echo route("teachers"); ?>#site_pro">Les sites de professionnels</a></li>
                                    <li><a href="<?php echo route("teachers"); ?>#site_particuliers">Les sites de particuliers</a></li>
                                </ul>

                            </li>
                            <li class="has-children">
                                <a href="<?php echo route("teachers"); ?>#academique">La formation académique</a>
                                <ul class="sous-menu">
                                    <li><a href="<?php echo route("teachers"); ?>#ecole">Les écoles</a></li>
                                    <li><a href="<?php echo route("teachers"); ?>#cursus">Les cursus</a></li>
                                </ul>

                            </li>
                            <li class="has-children">
                                <a href="<?php echo route("teachers"); ?>#form_pro">La formation professionnelle</a>
                                <ul class="sous-menu">
                                    <li><a href="<?php echo route("teachers"); ?>#rncp">Les titres RNCP</a></li>
                                    <li><a href="<?php echo route("teachers"); ?>#ecole_pro">Les écoles</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li class="has-children">
                        <a href="<?php echo route("ide"); ?>">IDE et EDT</a>
                        <ul class="sous-menu">
                            <li><a href="<?php echo route("ide"); ?>#choisir_ide">Comment choisir</a></li>
                            <li><a href="<?php echo route("ide"); ?>#best_ide">Top 3 des IDE et EDT</a></li>
                        </ul>
                    </li>
                    <li class="has-children">
                        <a href="<?php echo route("languages"); ?>">Langages, Frameworks, CMS</a>
                        <ul class="sous-menu">
                            <li><a href="<?php echo route("languages"); ?>#langage">Langages de programmation</a></li>
                            <li><a href="<?php echo route("languages"); ?>#frameworks">Frameworks</a></li>
                            <li><a href="<?php echo route("languages"); ?>#cms">CMS</a></li>
                        </ul>
                    </li>
                    <li class="has-children">
                        <a href="<?php echo route("software"); ?>">Outils à connaître</a>
                        <ul class="sous-menu">

                            <li><a href="<?php echo route("software"); ?>#inspecteur">L'inspecteur</a></li>
                            <li><a href="<?php echo route("software"); ?>#validator">Le validator</a></li>
                            <li><a href="<?php echo route("software"); ?>#fontawesome">FontAwesome</a></li>
                            <li><a href="<?php echo route("software"); ?>#googlefonts">GoogleFonts</a></li>
                            <li><a href="<?php echo route("software"); ?>#git">Git</a></li>
                            <li><a href="<?php echo route("software"); ?>#nodeJs">Node JS</a></li>
                            <li><a href="<?php echo route("software"); ?>#browsersync">Browsersync</a></li>
                            <li><a href="<?php echo route("software"); ?>#site_web_recommandés">Sites web</a></li>
                        </ul>
                    </li>
                    <li class="has-children">
                        <a href="<?php echo route("portefolio"); ?>">Portefolio</a>
                        <ul class="sous-menu">

                            <li><a href="<?php echo route("portefolio"); ?>#dragon">Dragon Slayer </a></li>
                            <li><a href="<?php echo route("portefolio"); ?>#funny_slider">Funny Slider</a></li>
                            <li><a href="<?php echo route("portefolio"); ?>#address_book">Carnet d'adresse</a></li>
                            <li><a href="<?php echo route("portefolio"); ?>#gif_generator">Gif Generator</a></li>


                        </ul>
                    </li>
                </ul>
                </nav>
            </header>
            <main >
                <div id="content">
                    <?php echo $viewContent ?>
                </div>
            </main>
            <footer class=" footer">
                <p class="pf">Copyright 2018 - Tous droits réservés</p>
            </footer>
        </div>
            <script>
                var base_url="<?php echo BASE_URL;?>";
            </script>
            <script src="<?php echo BASE_URL?>/js/event.js"></script>
            <script src="<?php echo BASE_URL?>/js/addressbook.js"></script>
            <script src="<?php echo BASE_URL?>/js/funny_slider.js"></script>
            <script src="<?php echo BASE_URL?>/js/gif_generator.js"></script>
            <script src="<?php echo BASE_URL?>/js/app.js"></script>
            <script src="<?php echo BASE_URL?>/js/utilities.js"></script>
            <script src="<?php echo BASE_URL?>/js/dragon_slayer.js"></script>
    </body>

</html>