
	<main class="main2child">
		<section class="section-gauche marginBottom25">
			<h2 id="environnement">Comprendre son environnement</h2>
			<ol>
				<li>
					<h3 id="os">A- Système d'exploitation</h3>

					<ul class="square">
						<li>ES en français, OS en anglais (Operating System)</li>
						<li>C'est l'ensemble des programmes qui pilotent les différents composants de l'appareil informatique.</li>
						<li>Les pilotes (drivers en anglais), constituent le lien de communication entre l'OS et ces composants. </li>
						<li>Il existe 3 OS pour pour PC: Windows, MacOS et Linux. Il y en a également 3 pour les mobiles: Android, IOS et Windows 10 mobile.</li>
						<li>PC: 
							<p><i class="fab fa-windows"></i>Windows est le plus utilisé (90% des PC l'ont en pré-installation). Il n'est pas open source: le code de cet OS n'est pas laissé en libre accès et ne peut être réutiliser ou modifier.
							</p> 
							<p><i class="fab fa-apple"></i>Mac appartient à Apple, son code source est également fermé.</p> 
							<p><i class="fab fa-linux"></i>Enfin Linux (GNU/Linux) est open source. Par conséquent, il possède de nombreux distributeurs différents (logiciels calqués sur ce code). Attention, ce n'est pas parce qu'un code est open source, qu'il est gratuit!</p>
						</li>
						<li>Mobile: 
							<p><i class="fab fa-android"></i>Android est un OS basé sur le noyau Linus et est l'OS le plus utilisé (80% des smartphones). </p>
							<p><i class="fab fa-apple"></i>En 2ème position, arrive l'IOS d'Apple.</p>
							<p><i class="fab fa-windows"></i>Quant à Windows 10 mobile, il est très faiblement utilisé. On le trouve sur les téléphones Nokia et autres smartphones développés par Windows.</p> 
						</li>
					</ul>
				</li>
				<li>
					<h3 id="clavier">B- Le clavier</h3>
					<ul class="lower-hexadecimal">
						<li class="h4">
							<h4>1- La présentation du clavier</h4>
						</li>
						<li><p>Inutile d'avancer plus loin si vous ne savez repérer la touche Tab du clavier!!! Voici <a href="<?php echo BASE_URL?>/documents/clavier.pdf" target="_blank"> un document</a> de présentation des différentes touches. A connaître absolument!</p></li>
						<li class="h4">
							<h4>2- Les raccourcis clavier</h4>
						</li>
						<li><p>Vous pouvez bien entendu coder sans raccourcis. Vous pouvez également faire Lille - Paris à pieds. L'on admettra cependant que la chose est plus aisée en train ou en voiture. Le principe est le même. Vous pouvez vous amuser à faire des copier coller avec la souris voire avec l'onglet "fichier". Ou vous pouvez aussi faire un ctrl+c et ctrl+v. Ci-joint <a href="<?php echo BASE_URL?>/documents/raccourcis_clavier_windows.docx">un document </a> de raccourcis clavier que vous pourrez modifier à votre guise. Au cas où vous chercheriez la même chose pour les symboles, voilà <a href="<?php echo BASE_URL?>/documents/symbole-clavier.pdf" target="_blank">un autre document</a> adapté.</p></li>
						<li class="h4">
							<h4>3- Les raccourcis Emmet</h4>
						</li>
						<li><p>Une fois cette base acquise, l'on peut encore se faciliter la tâche avec les raccourcis de votre IDE ou éditeur de texte. Puisqu'il s'agît du logiciel que j'utilise, voici <a href="<?php echo BASE_URL?>/documents/raccourcis-emmet.pdf" target="_blank"> un document</a> de raccourcis d'Emmet. Ces raccourcis rendront votre vie plus belle, je vous l'assure!</p></li>

					</ul>
				</li>
				<li>
				<li>
					<h3 id="cli">C- L'invite de commande</h3>
				</li>
				<li>
					<ul class="lower-hexadecimal">
						<li class="h4"><h4>1- Qu'est-ce qu'une invite de commande ?</h4></li>
						<li><p>L'invite de commande c'est la manière brut de donner des ordres bien spécifiques à votre PC. Ici, pas de design cool, pas d'applications intermédiaires. C'est l'occasion de lui dire en face tout ce que vous aviez sur le coeur !</p>
							<p>Les instructions sont diverses et variées, vous pouvez demander de créer un fichier, d'exécuter un programme...</p></li>
						<li class="h4"><h4>2- Avec Git</h4></li>
						<li><p>Git est un logiciel qui vous permet de travailler sur différentes versions de votre code. Vous aurez donc besoin d'enregistrer ces versions différentes, de récupérer ce que vos collègues auront fait de leur côté et enfin de merger le code qui vous satisfait à celui qui servira à la production. Pour ce faire, l'invite de commande vous sera précieuse.</p></li>
						<li class="h4"><h4>3- Avec Node JS</h4></li>
						<li><p>Node JS est un outil sur lequel vous trouverez plus d'amples informations à la page logiciels. Je vous invite à vous y rendre et découvrir les vidéos de Grafikart dessus.</p></li>
					</ul>
				</li>
					<li>
                <li>
                    <h3 id="vocabulaire">D- Vocabulaire informatique</h3>
                </li>
                    <li>
						<ul class="square">
							<li>Inutile de vous convaincre qu'il est préférable de comprendre les termes utilisés lors d'une conversation. Bien évidemment, s'il n'y a pas de recherche personnelle, attendez-vous à des subir des situations humiliantes de manière fréquente, voire pour les "vainqueurs" à être invité à des dîners le mardi!</li>
							<li>Allez, un cadeau, voici un lien vers <a href="https://definition-marketing.net/domaine/informatique-webmastering/">un site de définition et d'aide</a> que vous pourrez accompagner avec ce lien vers un <a href="https://www.vulgarisation-informatique.com/lexique.php" target="_blank">second lexique.</a></li>
						</ul>
					</li>

				</ol>
			</section>
			<section class="section-droite">
				<h2 id="metier">Comprendre le métier
				</h2>	
				<ul>
					<li><h3 id="client" class="step">Etape 1: Le client - l'idée</h3>
						<p>L'origine de la demande et plus important encore, le payeur!!! C'est le propriétaire d'un restaurant, d'une école, d'une start-up... En fait, n'importe quelle entreprise et organisme aujourd'hui aura besoin d'une certaine publicité et cela, quelque soit son domaine d'activité. Du producteur de miel au vendeur d'assurance, en passant par votre dentiste.</p>
					</li> 

					<li><h3 id="protypeur" class="step">Etape 2: Le Protypeur - La structure</h3>


						<p>Il s'appelle aussi "wireframe" en entreprise. Il établit un document de référence sur ce à quoi le site devrait ressembler une fois terminé. Mais le protypeur peut également n'être autre que le client! Lorsque c'est le cas, alors chaque document de référence ne sera généralement qu'une simple feuille A4 avec un croquis d'une page du futur site web. (Oui, ça sent le vécut, et alors?)</p>
					</li>

					<li><h3 id="webdesigner" class="step">Etape 3: Le Webdesigner - le visuel</h3>


						<p>Grâce au document de référence fourni, il produit une maquette graphique à l'aide d'un logiciel (ex: Photoshop). Il ne faut pas le confondre avec le webmaster dont le travail est plus large et sera chargé de superviser l'analyse quotidienne et l'aspect fonctionnel du site. Aussi appelé "designer graphique", le webdesigner peut également multiplier les casquettes et être intégrateur. </p>
					</li> 

					<li><h3 id="integrateur" class="step">Etape 4: L'intégrateur Web - le fonctionnel</h3>

						<p>Il créé une maquette fonctionnelle en la codant en html, css et dans une moindre mesure en JavaScript. Il optimise son référencement et veille à ce que son code soit fonctionnel sur tous les navigateurs ( mozilla, chrome, Internet Explorer...) ainsi que sur toutes les plateformes (PC, portable, tablette...) Pour ceux qui sous-estime l'importance de l'intégration, vous n'avez qu'à penser à tout ces sites internet qui manque de visibilité car les mots sont superposés voire manquant. Et bien clairement, les concepteurs n'avaient pas les moyens de se payer un intégrateur. Un site dégueulasse à voire est un site que les clients fuiront si concurrence il y a!!! </p>
					</li> 

					<li><h3 id="front" class="step">Etape 5: Le développeur front-end - la production frontale</h3>

						<p>Il complète le code avec un contenu réel et usera de JavaScript dans une plus grande mesure  que l'intégrateur afin de rendre le site plus dynamique. Il gère ce qu'on appelle la partie client ou partie interface. Bref, il code la partie visible de l'iceberg, partie avec laquelle l'internaute pourra interagir. Avec lui, on entre dans le monde des algorithmes. Il aura le lourd travail de poser différents types de réactions informatiques en fonction du comportement du navigateur. (J'ai pas mal paraphraser, alors ceux qui n'ont pas compris, laissez-moi tranquille, j'ai fait de mon mieux!) Encore une fois, il est possible que le développeur joue deux rôles et soit à la fois front-end et back-end, on dit de lui qu'il est un développeur full-stack!</p>
					</li> 

					<li><h3 id="back" class="step">Etape 6: Le développeur back-end - la production en arrière plan</h3>
						<p>Il complète de la même manière le code que le développeur front-end, mais côté serveur. Pour ce faire, il usera essentiellement le langage PHP et le système de gestion de bases de données MySQL. Imaginez-vous une inscription sur un site. Vous devrez répondre à des questions dans des champs prédéfinis (ex: Age, Nom, Prénom, Mail...) Ou mieux, imaginez-vous un site e-commerce ou vous devrez à l'identique remplir des champs en fonction des produits que vous souhaitez acheter. Pendant que vous vous occupez de cliquer sur deux, trois boutons, il y a des développeurs qui ont coder pour que vos commandes soient prisent en compte. Que dis-je, pour que vous ayez même la possibilité de commander quelque chose.</p>
					</li> 
				</ul>
				<div class="conclusion">
					<h3>Conclusion</h3>
					<p class="italic">Avec le temps, la plus part des développeurs professionnels en viennent à se spécialiser. Toutefois les développeurs full-stack sont des profils très recherchés par les start-up et petites entreprises. En effet, elles diminuent leurs frais en engageant différents corps de métiers en une seule et même personne. En fonction de votre projet, il faudra se spécialiser dans différents langages de programmation. Ce site abordera essentiellement les 3 derniers degrés de la création d'un site web, c'est à dire le travail de l'intégrateur et des développeurs. Les premières étapes seront aperçues superficiellement dans le cas où une seule personne ferait tout le travail.
					</p> 
					<p class="bold">Alors, maintenant que vous savez parfaitement différencier tous ces jobs, la grande question est : le(s) quel(s) vous intéresse(nt)?
					</p> 
				</div>
			</section>
		</main>
